[package]
name = "repl"
version = "0.1.0"
authors = ["dougfort <doug.fort@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bel = { path = "../bel" }
anyhow = "1"
rustyline = "9"
